import { registerCalculator } from "@/lib/registry";
import type { CalculatorConfig } from "./calculator-schema";

const config = {
  slug: "churn-calculator",
  category: "churn-retention",
  meta: {
    title: "Churn Rate Calculator",
    description: "Calculate your monthly and annual churn rate to understand customer retention.",
    keywords: ["churn", "churn rate", "customer retention", "saas metrics", "monthly churn", "annual churn"],
  },
  benchmarkMetric: "churn-rate",
  inputs: [
    { id: "customersStart", label: "Customers at Period Start", type: "number" as const, defaultValue: 1000 },
    { id: "customersEnd", label: "Customers at Period End", type: "number" as const, defaultValue: 950 },
    { id: "lostCustomers", label: "Customers Lost in Period", type: "number" as const, defaultValue: 50 },
  ],
  outputs: [
    { id: "monthlyChurnPct", label: "Monthly Churn Rate", type: "percentage" as const, isPrimary: true },
    { id: "annualChurnPct", label: "Annual Churn Rate", type: "percentage" as const, isPrimary: false },
    { id: "retainedCustomers", label: "Retained Customers", type: "number" as const, isPrimary: false },
  ],
  content: {
    intro: "Churn rate measures the percentage of customers who stop using your product during a given period. It is arguably the most critical retention metric for subscription businesses because it directly impacts revenue, growth, and customer lifetime value. A high churn rate means you must constantly acquire new customers just to maintain revenue levels, creating a 'leaky bucket' dynamic that limits growth. Reducing churn by even a few percentage points can dramatically improve your company's financial trajectory. Understanding both monthly and annual churn rates helps you benchmark against industry standards and set realistic retention goals.",
    howToUse: "Enter your customer count at the start and end of the period, plus the number of customers lost. The calculator computes both monthly and annualized churn rates, along with retained customer count. Use this data to track retention trends and identify periods of customer attrition.",
    formulaExplanation: "Monthly Churn Rate = (Lost Customers ÷ Starting Customers) × 100. Annual Churn Rate = 1 - (1 - Monthly Rate)^12. For example, if you start with 1,000 customers and lose 50: Monthly churn = (50 ÷ 1,000) × 100 = 5%. Annual churn = 1 - (1 - 0.05)^12 ≈ 46%.",
    benchmarks: "SaaS churn benchmarks vary by customer segment: SMB/self-serve averages 5-7% monthly churn, mid-market averages 3-5%, enterprise averages 1-2%, and top-quartile companies achieve under 1% monthly churn. According to Recurly Research 2025, median monthly churn across all subscription types is 4-6%. Annual churn for established SaaS companies typically ranges from 5-10% for enterprise to 30-50%+ for SMB.",
    benchmarkData: [
      { metric: "SMB Monthly Churn", value: "5 - 7%", source: "Recurly Research 2025" },
      { metric: "Mid-Market Monthly Churn", value: "3 - 5%", source: "Recurly Research 2025" },
      { metric: "Enterprise Monthly Churn", value: "1 - 2%", source: "Recurly Research 2025" },
      { metric: "Top-Quartile Monthly Churn", value: "< 1%", source: "KeyBanc 2025" },
      { metric: "Healthy Annual Churn (Enterprise)", value: "5 - 10%", source: "SaaS Capital" },
    ],
    relatedCalculators: ["mrr-calculator", "ltv-calculator", "arpu-calculator", "customer-health-score-calculator", "nrr-calculator"],
    faq: [
      { question: "What is a good churn rate?", answer: "For SaaS, 3-5% monthly churn is average for SMB, while enterprise SaaS aims for 1-2% or lower. Under 1% monthly is world-class. Annual churn under 10% is considered healthy." },
      { question: "Should I include voluntary and involuntary churn?", answer: "Yes. Track both types separately but include both in your total churn calculation for accuracy. Voluntary churn (customers who cancel) and involuntary churn (failed payments) require different solutions. Reduce involuntary churn with dunning tools like [Baremetrics](https://baremetrics.com?via=saastainednumbers)." },
      { question: "What is the difference between logo churn and revenue churn?", answer: "Logo churn tracks customer count; revenue churn tracks MRR lost. Revenue churn can be lower than logo churn if lost customers were low-paying and remaining customers upgrade." },
      { question: "How do I reduce monthly churn rate?", answer: "Focus on onboarding improvement (reduce time-to-value), proactive customer success (reach out before renewal), pricing optimization (right-size plans), and product improvements based on churn feedback. Use [ChurnZero](https://churnzero.com) for proactive customer success automation." },
      { question: "What is a healthy annual churn rate for SaaS?", answer: "Under 10% annual churn is excellent. 10-20% is average. Above 20% needs immediate attention. Enterprise SaaS often achieves 5-7% annual churn." },
      { question: "How do I calculate churn for a new product with few customers?", answer: "Use cohort analysis. Track groups of customers who joined in the same month and measure their retention over time. This gives more reliable data than overall churn for small customer bases." },
      { question: "What causes involuntary churn?", answer: "Failed payments are the primary cause of involuntary churn. Implement dunning (automatic retry), email reminders before card expiry, and multiple payment methods to reduce it." },
      { question: "How does churn rate affect company valuation?", answer: "Dramatically. Lower churn means higher LTV, more predictable revenue, and lower replacement costs. Investors heavily weight churn rate when valuing SaaS companies. A company with 5% monthly churn needs to replace half its customer base every year, severely limiting growth potential and commanding a lower revenue multiple." },
      { question: "What industries have the lowest churn rates?", answer: "Enterprise SaaS and B2B companies with long-term contracts typically have the lowest churn rates (1-2% monthly). Subscription boxes and consumer apps tend to have higher churn (5-10% monthly). Fintech and healthcare SaaS products often see under 3% monthly churn due to high switching costs and integration depth." },
      { question: "Can churn rate be negative?", answer: "No, churn rate cannot technically be negative  -  it represents customers lost. However, if you gained more customers than you lost, your net growth is positive. What some call 'negative churn' actually refers to net negative revenue churn, where expansion revenue from existing customers exceeds revenue lost to churn. This is a sign of a healthy SaaS business with strong upsell motion." },
      { question: "What is the difference between voluntary and involuntary churn and how do I reduce each?", answer: "Voluntary churn happens when customers actively cancel due to dissatisfaction, cost, or lack of need. Reduce it with better onboarding, engagement workflows, and product improvements. Involuntary churn occurs from failed payments  -  expired cards, insufficient funds. Reduce it with dunning emails, automatic retries, and backup payment methods. Involuntary churn is often easier to fix and can account for 20-40% of total churn." },
    ],
  },
  locales: {
    es: {
      meta: {
        title: "Calculadora de Tasa de Churn",
        description: "Calcula tu tasa de churn mensual y anual para entender la retención de clientes.",
      },
      inputs: [
        { id: "customersStart", label: "Clientes al Inicio del Período" },
        { id: "customersEnd", label: "Clientes al Final del Período" },
        { id: "lostCustomers", label: "Clientes Perdidos en el Período" },
      ],
      outputs: [
        { id: "monthlyChurnPct", label: "Tasa de Churn Mensual" },
        { id: "annualChurnPct", label: "Tasa de Churn Anual" },
        { id: "retainedCustomers", label: "Clientes Retenidos" },
      ],
      content: {
        intro: "La tasa de churn mide el porcentaje de clientes que dejan de usar tu producto durante un período determinado. Es posiblemente la métrica de retención más crítica para las empresas de suscripción porque impacta directamente en los ingresos, el crecimiento y el valor de vida del cliente. Una tasa de churn alta significa que debes adquirir constantemente nuevos clientes solo para mantener los niveles de ingresos, creando una dinámica de 'cubo con fugas' que limita el crecimiento. Reducir el churn aunque sea unos pocos puntos porcentuales puede mejorar drásticamente la trayectoria financiera de tu empresa. Comprender tanto las tasas de churn mensual como anual te ayuda a compararte con los estándares de la industria y establecer objetivos de retención realistas.",
        howToUse: "Ingresa tu número de clientes al inicio y al final del período, más la cantidad de clientes perdidos. La calculadora calcula tanto las tasas de churn mensual como anualizada, junto con la cantidad de clientes retenidos. Usa estos datos para rastrear tendencias de retención e identificar períodos de pérdida de clientes.",
        formulaExplanation: "Tasa de Churn Mensual = (Clientes Perdidos ÷ Clientes Iniciales) × 100. Tasa de Churn Anual = 1 - (1 - Tasa Mensual)^12. Por ejemplo, si comienzas con 1,000 clientes y pierdes 50: Churn mensual = (50 ÷ 1,000) × 100 = 5%. Churn anual = 1 - (1 - 0.05)^12 ≈ 46%.",
        benchmarks: "Los benchmarks de churn SaaS varían según el segmento de clientes: SMB/autoservicio promedia 5-7% de churn mensual, mercado medio promedia 3-5%, enterprise promedia 1-2%, y las empresas del cuartil superior logran menos del 1% de churn mensual. Según Recurly Research 2025, la mediana de churn mensual en todos los tipos de suscripción es del 4-6%.",
        benchmarkData: [
          { metric: "Churn Mensual SMB", value: "5 - 7%", source: "Recurly Research 2025" },
          { metric: "Churn Mensual Mercado Medio", value: "3 - 5%", source: "Recurly Research 2025" },
          { metric: "Churn Mensual Enterprise", value: "1 - 2%", source: "Recurly Research 2025" },
          { metric: "Churn Mensual Cuartil Superior", value: "< 1%", source: "KeyBanc 2025" },
          { metric: "Churn Anual Saludable (Enterprise)", value: "5 - 10%", source: "SaaS Capital" },
        ],
        faq: [
          { question: "¿Qué es una buena tasa de churn?", answer: "Para SaaS, 3-5% de churn mensual es promedio para SMB, mientras que el SaaS enterprise apunta a 1-2% o menos. Menos del 1% mensual es de clase mundial." },
          { question: "¿Debo incluir el churn voluntario e involuntario?", answer: "Sí. Rastrea ambos tipos por separado pero incluye ambos en tu cálculo total de churn para precisión. El churn voluntario (clientes que cancelan) y el churn involuntario (pagos fallidos) requieren soluciones diferentes." },
          { question: "¿Cuál es la diferencia entre churn de clientes y churn de ingresos?", answer: "El churn de clientes rastrea la cantidad de clientes; el churn de ingresos rastrea el MRR perdido. El churn de ingresos puede ser menor que el churn de clientes si los clientes perdidos pagaban poco." },
          { question: "¿Cómo reduzco la tasa de churn mensual?", answer: "Concéntrate en mejorar la incorporación (reducir el tiempo de valor), el éxito proactivo del cliente (comunicarte antes de la renovación), la optimización de precios (planes adecuados) y las mejoras de producto basadas en comentarios de churn." },
          { question: "¿Qué es una tasa de churn anual saludable para SaaS?", answer: "Menos del 10% de churn anual es excelente. 10-20% es promedio. Más del 20% necesita atención inmediata." },
          { question: "¿Cómo calculo el churn para un producto nuevo con pocos clientes?", answer: "Usa análisis de cohortes. Rastrea grupos de clientes que se unieron en el mismo mes y mide su retención a lo largo del tiempo." },
          { question: "¿Qué causa el churn involuntario?", answer: "Los pagos fallidos son la causa principal del churn involuntario. Implementa dunning (reintento automático), recordatorios por correo electrónico antes del vencimiento de la tarjeta y múltiples métodos de pago." },
          { question: "¿Cómo afecta la tasa de churn a la valoración de la empresa?", answer: "Drásticamente. Un churn más bajo significa un LTV más alto, ingresos más predecibles y menores costos de reemplazo. Los inversores ponderan fuertemente la tasa de churn al valorar empresas SaaS." },
          { question: "¿Qué industrias tienen las tasas de churn más bajas?", answer: "Las empresas SaaS enterprise y B2B con contratos a largo plazo típicamente tienen las tasas de churn más bajas (1-2% mensual). Fintech y SaaS de salud a menudo ven menos del 3% de churn mensual." },
            { question: "¿Puede la tasa de churn ser negativa?", answer: "No, la tasa de churn técnicamente no puede ser negativa; representa clientes perdidos. El 'churn negativo' en realidad se refiere al churn de ingresos neto negativo, donde los ingresos por expansión superan los ingresos perdidos por churn." },
          { question: "¿Cuál es la diferencia entre churn voluntario e involuntario y cómo reduzco cada uno?", answer: "El churn voluntario ocurre cuando los clientes cancelan activamente. Redúcelo con una mejor incorporación y mejoras de producto. El churn involuntario ocurre por pagos fallidos. Redúcelo con correos de dunning y reintentos automáticos." },
        ],
      },
    },
    de: {
      meta: {
        title: "Churn-Rate-Rechner",
        description: "Berechnen Sie Ihre monatliche und jährliche Abwanderungsrate, um die Kundenbindung zu verstehen.",
      },
      inputs: [
        { id: "customersStart", label: "Kunden zu Periodenbeginn" },
        { id: "customersEnd", label: "Kunden am Periodenende" },
        { id: "lostCustomers", label: "Verlorene Kunden im Zeitraum" },
      ],
      outputs: [
        { id: "monthlyChurnPct", label: "Monatliche Abwanderungsrate" },
        { id: "annualChurnPct", label: "Jährliche Abwanderungsrate" },
        { id: "retainedCustomers", label: "Verbleibende Kunden" },
      ],
      content: {
        intro: "Die Abwanderungsrate misst den Prozentsatz der Kunden, die Ihr Produkt in einem bestimmten Zeitraum nicht mehr nutzen. Sie ist wohl die wichtigste Bindungsmetrik für Abonnementunternehmen, da sie sich direkt auf Umsatz, Wachstum und den Customer Lifetime Value auswirkt. Eine hohe Abwanderungsrate bedeutet, dass Sie ständig neue Kunden gewinnen müssen, nur um das Umsatzniveau zu halten, was eine 'Undichte-Eimer'-Dynamik erzeugt, die das Wachstum einschränkt. Die Reduzierung der Abwanderung um nur wenige Prozentpunkte kann die finanzielle Entwicklung Ihres Unternehmens dramatisch verbessern. Das Verständnis sowohl der monatlichen als auch der jährlichen Abwanderungsrate hilft Ihnen, sich mit Branchenstandards zu vergleichen und realistische Bindungsziele zu setzen.",
        howToUse: "Geben Sie Ihre Kundenzahl zu Beginn und am Ende des Zeitraums sowie die Anzahl der verlorenen Kunden ein. Der Rechner berechnet sowohl die monatliche als auch die annualisierte Abwanderungsrate sowie die Anzahl der verbleibenden Kunden. Nutzen Sie diese Daten, um Bindungstrends zu verfolgen und Zeiträume mit Kundenabwanderung zu identifizieren.",
        formulaExplanation: "Monatliche Abwanderungsrate = (Verlorene Kunden ÷ Startkunden) × 100. Jährliche Abwanderungsrate = 1 - (1 - Monatsrate)^12. Beispiel: Wenn Sie mit 1.000 Kunden starten und 50 verlieren: Monatliche Abwanderung = (50 ÷ 1.000) × 100 = 5%. Jährliche Abwanderung = 1 - (1 - 0,05)^12 ≈ 46%.",
        benchmarks: "SaaS-Abwanderungsbenchmarks variieren je nach Kundensegment: SMB/Self-Service durchschnittlich 5-7% monatliche Abwanderung, Mid-Market durchschnittlich 3-5%, Enterprise durchschnittlich 1-2% und Top-Quartil-Unternehmen erreichen unter 1% monatliche Abwanderung. Laut Recurly Research 2025 liegt die mediane monatliche Abwanderung über alle Abonnementtypen bei 4-6%.",
        benchmarkData: [
          { metric: "Monatliche Abwanderung SMB", value: "5 - 7%", source: "Recurly Research 2025" },
          { metric: "Monatliche Abwanderung Mid-Market", value: "3 - 5%", source: "Recurly Research 2025" },
          { metric: "Monatliche Abwanderung Enterprise", value: "1 - 2%", source: "Recurly Research 2025" },
          { metric: "Monatliche Abwanderung Top-Quartil", value: "< 1%", source: "KeyBanc 2025" },
          { metric: "Gesunde jährliche Abwanderung (Enterprise)", value: "5 - 10%", source: "SaaS Capital" },
        ],
        faq: [
          { question: "Was ist eine gute Abwanderungsrate?", answer: "Für SaaS sind 3-5% monatliche Abwanderung für SMB durchschnittlich, während Enterprise-SaaS auf 1-2% oder weniger abzielt. Unter 1% monatlich ist Weltklasse." },
          { question: "Sollte ich freiwillige und unfreiwillige Abwanderung einbeziehen?", answer: "Ja. Verfolgen Sie beide Arten getrennt, beziehen Sie aber beide in Ihre Gesamtabwanderungsberechnung zur Genauigkeit ein. Freiwillige Abwanderung (Kunden, die kündigen) und unfreiwillige Abwanderung (fehlgeschlagene Zahlungen) erfordern unterschiedliche Lösungen." },
          { question: "Was ist der Unterschied zwischen Kundenabwanderung und Umsatzabwanderung?", answer: "Die Kundenabwanderung verfolgt die Kundenzahl; die Umsatzabwanderung verfolgt den verlorenen MRR. Die Umsatzabwanderung kann niedriger sein als die Kundenabwanderung, wenn die verlorenen Kunden wenig bezahlt haben." },
          { question: "Wie reduziere ich die monatliche Abwanderungsrate?", answer: "Konzentrieren Sie sich auf die Verbesserung des Onboardings (Reduzierung der Time-to-Value), proaktiven Customer Success (Kontaktaufnahme vor Verlängerung), Preisanpassung (passende Pläne) und Produktverbesserungen basierend auf Abwanderungsfeedback." },
          { question: "Was ist eine gesunde jährliche Abwanderungsrate für SaaS?", answer: "Unter 10% jährliche Abwanderung ist ausgezeichnet. 10-20% ist durchschnittlich. Über 20% erfordert sofortige Aufmerksamkeit." },
          { question: "Wie berechne ich die Abwanderung für ein neues Produkt mit wenigen Kunden?", answer: "Verwenden Sie eine Kohortenanalyse. Verfolgen Sie Gruppen von Kunden, die im selben Monat beigetreten sind, und messen Sie deren Bindung im Laufe der Zeit." },
          { question: "Was verursacht unfreiwillige Abwanderung?", answer: "Fehlgeschlagene Zahlungen sind die Hauptursache für unfreiwillige Abwanderung. Implementieren Sie Dunning (automatischer Wiederholungsversuch), E-Mail-Erinnerungen vor Kartenablauf und mehrere Zahlungsmethoden." },
          { question: "Wie wirkt sich die Abwanderungsrate auf die Unternehmensbewertung aus?", answer: "Dramatisch. Niedrigere Abwanderung bedeutet höheren LTV, vorhersehbarere Umsätze und geringere Ersatzkosten. Investoren gewichten die Abwanderungsrate bei der Bewertung von SaaS-Unternehmen stark." },
          { question: "Welche Branchen haben die niedrigsten Abwanderungsraten?", answer: "Enterprise-SaaS und B2B-Unternehmen mit langfristigen Verträgen haben typischerweise die niedrigsten Abwanderungsraten (1-2% monatlich). Fintech und Healthcare-SaaS verzeichnen oft unter 3% monatliche Abwanderung." },
            { question: "Kann die Abwanderungsrate negativ sein?", answer: "Nein, die Abwanderungsrate kann technisch nicht negativ sein; sie repräsentiert verlorene Kunden. 'Negative Abwanderung' bezieht sich tatsächlich auf eine negative Netto-Umsatzabwanderung, bei der der Expansionsumsatz den durch Abwanderung verlorenen Umsatz übersteigt." },
          { question: "Was ist der Unterschied zwischen freiwilliger und unfreiwilliger Abwanderung und wie reduziere ich jede?", answer: "Freiwillige Abwanderung tritt auf, wenn Kunden aktiv kündigen. Reduzieren Sie sie mit besserem Onboarding und Produktverbesserungen. Unfreiwillige Abwanderung entsteht durch fehlgeschlagene Zahlungen. Reduzieren Sie sie mit Dunning-E-Mails und automatischen Wiederholungsversuchen." },
        ],
      },
    },
    pt: {
      meta: {
        title: "Calculadora de Taxa de Churn",
        description: "Calcule sua taxa de churn mensal e anual para entender a retenção de clientes.",
      },
      inputs: [
        { id: "customersStart", label: "Clientes no Início do Período" },
        { id: "customersEnd", label: "Clientes no Final do Período" },
        { id: "lostCustomers", label: "Clientes Perdidos no Período" },
      ],
      outputs: [
        { id: "monthlyChurnPct", label: "Taxa de Churn Mensal" },
        { id: "annualChurnPct", label: "Taxa de Churn Anual" },
        { id: "retainedCustomers", label: "Clientes Retidos" },
      ],
      content: {
        intro: "A taxa de churn mede a porcentagem de clientes que param de usar seu produto durante um determinado período. É possivelmente a métrica de retenção mais crítica para negócios de assinatura porque impacta diretamente a receita, o crescimento e o valor do tempo de vida do cliente. Uma alta taxa de churn significa que você precisa adquirir constantemente novos clientes apenas para manter os níveis de receita, criando uma dinâmica de 'balde furado' que limita o crescimento. Reduzir o churn em apenas alguns pontos percentuais pode melhorar drasticamente a trajetória financeira da sua empresa. Entender tanto as taxas de churn mensal quanto anual ajuda você a comparar com os padrões da indústria e definir metas de retenção realistas.",
        howToUse: "Insira seu número de clientes no início e no final do período, mais o número de clientes perdidos. A calculadora calcula as taxas de churn mensal e anualizada, junto com o número de clientes retidos. Use esses dados para acompanhar tendências de retenção e identificar períodos de perda de clientes.",
        formulaExplanation: "Taxa de Churn Mensal = (Clientes Perdidos ÷ Clientes Iniciais) × 100. Taxa de Churn Anual = 1 - (1 - Taxa Mensal)^12. Por exemplo, se você começar com 1.000 clientes e perder 50: Churn mensal = (50 ÷ 1.000) × 100 = 5%. Churn anual = 1 - (1 - 0,05)^12 ≈ 46%.",
        benchmarks: "Os benchmarks de churn SaaS variam por segmento de cliente: SMB/autoatendimento tem média de 5-7% de churn mensal, médio mercado tem média de 3-5%, enterprise tem média de 1-2%, e empresas do quartil superior alcançam menos de 1% de churn mensal. De acordo com a Recurly Research 2025, a mediana de churn mensal em todos os tipos de assinatura é de 4-6%.",
        benchmarkData: [
          { metric: "Churn Mensal SMB", value: "5 - 7%", source: "Recurly Research 2025" },
          { metric: "Churn Mensal Médio Mercado", value: "3 - 5%", source: "Recurly Research 2025" },
          { metric: "Churn Mensal Enterprise", value: "1 - 2%", source: "Recurly Research 2025" },
          { metric: "Churn Mensal Quartil Superior", value: "< 1%", source: "KeyBanc 2025" },
          { metric: "Churn Anual Saudável (Enterprise)", value: "5 - 10%", source: "SaaS Capital" },
        ],
        faq: [
          { question: "O que é uma boa taxa de churn?", answer: "Para SaaS, 3-5% de churn mensal é média para SMB, enquanto SaaS enterprise visa 1-2% ou menos. Abaixo de 1% mensal é classe mundial." },
          { question: "Devo incluir churn voluntário e involuntário?", answer: "Sim. Acompanhe ambos os tipos separadamente, mas inclua ambos no cálculo total de churn para precisão. Churn voluntário (clientes que cancelam) e churn involuntário (pagamentos falhos) exigem soluções diferentes." },
          { question: "Qual é a diferença entre churn de clientes e churn de receita?", answer: "O churn de clientes rastreia a quantidade de clientes; o churn de receita rastreia o MRR perdido. O churn de receita pode ser menor que o churn de clientes se os clientes perdidos pagavam pouco." },
          { question: "Como reduzo a taxa de churn mensal?", answer: "Concentre-se em melhorar a integração (reduzir o tempo para valor), sucesso proativo do cliente (entrar em contato antes da renovação), otimização de preços (planos adequados) e melhorias no produto com base no feedback de churn." },
          { question: "Qual é uma taxa de churn anual saudável para SaaS?", answer: "Abaixo de 10% de churn anual é excelente. 10-20% é média. Acima de 20% precisa de atenção imediata." },
          { question: "Como calculo o churn para um novo produto com poucos clientes?", answer: "Use análise de coorte. Acompanhe grupos de clientes que entraram no mesmo mês e meça sua retenção ao longo do tempo." },
          { question: "O que causa o churn involuntário?", answer: "Pagamentos falhos são a principal causa do churn involuntário. Implemente dunning (repetição automática), lembretes por e-mail antes do vencimento do cartão e múltiplos métodos de pagamento." },
          { question: "Como a taxa de churn afeta a valorização da empresa?", answer: "Drasticamente. Menor churn significa maior LTV, receita mais previsível e menores custos de substituição. Investidores pesam fortemente a taxa de churn ao avaliar empresas SaaS." },
          { question: "Quais indústrias têm as menores taxas de churn?", answer: "Empresas SaaS enterprise e B2B com contratos de longo prazo geralmente têm as menores taxas de churn (1-2% mensal). Fintech e SaaS de saúde frequentemente veem menos de 3% de churn mensal." },
            { question: "A taxa de churn pode ser negativa?", answer: "Não, a taxa de churn tecnicamente não pode ser negativa; ela representa clientes perdidos. 'Churn negativo' na verdade se refere ao churn de receita líquido negativo, onde a receita de expansão excede a receita perdida para o churn." },
          { question: "Qual é a diferença entre churn voluntário e involuntário e como reduzo cada um?", answer: "O churn voluntário acontece quando os clientes cancelam ativamente. Reduza-o com melhor integração e melhorias no produto. O churn involuntário ocorre por falhas de pagamento. Reduza-o com e-mails de dunning e repetições automáticas." },
        ],
      },
    },
    fr: {
      meta: {
        title: "Calculateur de Taux de Churn",
        description: "Calculez votre taux de churn mensuel et annuel pour comprendre la rétention client.",
      },
      inputs: [
        { id: "customersStart", label: "Clients en Début de Période" },
        { id: "customersEnd", label: "Clients en Fin de Période" },
        { id: "lostCustomers", label: "Clients Perdus sur la Période" },
      ],
      outputs: [
        { id: "monthlyChurnPct", label: "Taux de Churn Mensuel" },
        { id: "annualChurnPct", label: "Taux de Churn Annuel" },
        { id: "retainedCustomers", label: "Clients Retenus" },
      ],
      content: {
        intro: "Le taux de churn mesure le pourcentage de clients qui cessent d'utiliser votre produit au cours d'une période donnée. C'est sans doute la métrique de rétention la plus critique pour les entreprises par abonnement car elle impacte directement les revenus, la croissance et la valeur à vie du client. Un taux de churn élevé signifie que vous devez constamment acquérir de nouveaux clients juste pour maintenir vos niveaux de revenus, créant une dynamique de 'seau qui fuit' qui limite la croissance. Réduire le churn de seulement quelques points de pourcentage peut considérablement améliorer la trajectoire financière de votre entreprise. Comprendre à la fois les taux de churn mensuel et annuel vous aide à vous comparer aux normes de l'industrie et à définir des objectifs de rétention réalistes.",
        howToUse: "Saisissez votre nombre de clients au début et à la fin de la période, ainsi que le nombre de clients perdus. Le calculateur calcule à la fois les taux de churn mensuel et annualisé, ainsi que le nombre de clients retenus. Utilisez ces données pour suivre les tendances de rétention et identifier les périodes d'attrition client.",
        formulaExplanation: "Taux de Churn Mensuel = (Clients Perdus ÷ Clients de Départ) × 100. Taux de Churn Annuel = 1 - (1 - Taux Mensuel)^12. Par exemple, si vous commencez avec 1 000 clients et en perdez 50 : Churn mensuel = (50 ÷ 1 000) × 100 = 5 %. Churn annuel = 1 - (1 - 0,05)^12 ≈ 46 %.",
        benchmarks: "Les benchmarks de churn SaaS varient selon le segment de clientèle : PME/self-service a une moyenne de 5-7% de churn mensuel, le milieu de marché une moyenne de 3-5%, l'enterprise une moyenne de 1-2%, et les entreprises du quartile supérieur atteignent moins de 1% de churn mensuel. Selon Recurly Research 2025, le churn mensuel médian tous types d'abonnement confondus est de 4-6%.",
        benchmarkData: [
          { metric: "Churn Mensuel PME", value: "5 - 7%", source: "Recurly Research 2025" },
          { metric: "Churn Mensuel Milieu de Marché", value: "3 - 5%", source: "Recurly Research 2025" },
          { metric: "Churn Mensuel Enterprise", value: "1 - 2%", source: "Recurly Research 2025" },
          { metric: "Churn Mensuel Quartile Supérieur", value: "< 1%", source: "KeyBanc 2025" },
          { metric: "Churn Annuel Sain (Enterprise)", value: "5 - 10%", source: "SaaS Capital" },
        ],
        faq: [
          { question: "Qu'est-ce qu'un bon taux de churn ?", answer: "Pour le SaaS, 3-5% de churn mensuel est la moyenne pour les PME, tandis que le SaaS enterprise vise 1-2% ou moins. Moins de 1% par mois est de classe mondiale." },
          { question: "Dois-je inclure le churn volontaire et involontaire ?", answer: "Oui. Suivez les deux types séparément mais incluez les deux dans votre calcul total de churn pour plus de précision. Le churn volontaire (clients qui annulent) et le churn involontaire (paiements échoués) nécessitent des solutions différentes." },
          { question: "Quelle est la différence entre le churn de clients et le churn de revenus ?", answer: "Le churn de clients suit le nombre de clients ; le churn de revenus suit le MRR perdu. Le churn de revenus peut être inférieur au churn de clients si les clients perdus étaient peu rémunérateurs." },
          { question: "Comment réduire le taux de churn mensuel ?", answer: "Concentrez-vous sur l'amélioration de l'onboarding (réduire le time-to-value), le succès client proactif (contacter avant le renouvellement), l'optimisation des prix (plans adaptés) et les améliorations produit basées sur les retours de churn." },
          { question: "Quel est un taux de churn annuel sain pour le SaaS ?", answer: "Moins de 10% de churn annuel est excellent. 10-20% est la moyenne. Au-dessus de 20% nécessite une attention immédiate." },
          { question: "Comment calculer le churn pour un nouveau produit avec peu de clients ?", answer: "Utilisez l'analyse de cohorte. Suivez des groupes de clients qui ont rejoint le même mois et mesurez leur rétention dans le temps." },
          { question: "Qu'est-ce qui cause le churn involontaire ?", answer: "Les paiements échoués sont la principale cause du churn involontaire. Mettez en place du dunning (tentative automatique), des rappels par e-mail avant l'expiration de la carte et plusieurs méthodes de paiement." },
          { question: "Comment le taux de churn affecte-t-il la valorisation de l'entreprise ?", answer: "De façon dramatique. Un churn plus faible signifie un LTV plus élevé, des revenus plus prévisibles et des coûts de remplacement plus faibles. Les investisseurs accordent un poids important au taux de churn lors de l'évaluation des entreprises SaaS." },
          { question: "Quelles industries ont les taux de churn les plus bas ?", answer: "Les entreprises SaaS enterprise et B2B avec des contrats à long terme ont généralement les taux de churn les plus bas (1-2% par mois). La fintech et le SaaS santé enregistrent souvent moins de 3% de churn mensuel." },
            { question: "Le taux de churn peut-il être négatif ?", answer: "Non, le taux de churn ne peut techniquement pas être négatif; il représente les clients perdus. Le 'churn négatif' fait en réalité référence au churn de revenus net négatif, où les revenus d'expansion dépassent les revenus perdus par le churn." },
          { question: "Quelle est la différence entre le churn volontaire et involontaire et comment réduire chacun ?", answer: "Le churn volontaire se produit lorsque les clients annulent activement. Réduisez-le avec un meilleur onboarding et des améliorations produit. Le churn involontaire survient suite à des échecs de paiement. Réduisez-le avec des emails de dunning et des tentatives automatiques." },
        ],
      },
    },
    ja: {
      meta: {
        title: "チャーンレート計算機",
        description: "月次および年次のチャーンレートを計算し、顧客維持率を把握します。",
      },
      inputs: [
        { id: "customersStart", label: "期間開始時の顧客数" },
        { id: "customersEnd", label: "期間終了時の顧客数" },
        { id: "lostCustomers", label: "期間内に失った顧客数" },
      ],
      outputs: [
        { id: "monthlyChurnPct", label: "月次チャーンレート" },
        { id: "annualChurnPct", label: "年次チャーンレート" },
        { id: "retainedCustomers", label: "維持された顧客数" },
      ],
      content: {
        intro: "チャーンレートは、一定期間内に製品の使用をやめた顧客の割合を測定します。これは、収益、成長、顧客ライフタイムバリューに直接影響を与えるため、サブスクリプションビジネスにとって最も重要なリテンション指標です。高いチャーンレートは、収益レベルを維持するためだけに常に新規顧客を獲得しなければならず、成長を制限する「漏れのあるバケツ」のような状態を生み出します。チャーンを数パーセントポイント削減するだけで、企業の財務軌道を劇的に改善できます。月次と年次の両方のチャーンレートを理解することで、業界標準と比較し、現実的なリテンション目標を設定することができます。",
        howToUse: "期間開始時と終了時の顧客数、および失った顧客数を入力してください。計算機は月次および年次のチャーンレートと、維持された顧客数を算出します。このデータを使用してリテンションの傾向を追跡し、顧客減少の期間を特定してください。",
        formulaExplanation: "月次チャーンレート = (失った顧客数 ÷ 開始時の顧客数) × 100。年次チャーンレート = 1 - (1 - 月次レート)^12。例：1,000人の顧客で開始し50人を失った場合：月次チャーン = (50 ÷ 1,000) × 100 = 5%。年次チャーン = 1 - (1 - 0.05)^12 ≈ 46%。",
        benchmarks: "SaaSのチャーンベンチマークは顧客セグメントによって異なります：SMB/セルフサービスは平均月次チャーン5-7%、ミッドマーケットは平均3-5%、エンタープライズは平均1-2%、トップ四分位の企業は月次チャーン1%未満を達成しています。Recurly Research 2025によると、全サブスクリプションタイプの中央値の月次チャーンは4-6%です。",
        benchmarkData: [
          { metric: "SMB月次チャーン", value: "5 - 7%", source: "Recurly Research 2025" },
          { metric: "ミッドマーケット月次チャーン", value: "3 - 5%", source: "Recurly Research 2025" },
          { metric: "エンタープライズ月次チャーン", value: "1 - 2%", source: "Recurly Research 2025" },
          { metric: "トップ四分位月次チャーン", value: "< 1%", source: "KeyBanc 2025" },
          { metric: "健全な年次チャーン（エンタープライズ）", value: "5 - 10%", source: "SaaS Capital" },
        ],
        faq: [
          { question: "良いチャーンレートとは何ですか？", answer: "SaaSの場合、SMBでは月次チャーン3-5%が平均で、エンタープライズSaaSでは1-2%以下を目指します。月次1%未満はワールドクラスです。" },
          { question: "自発的チャーンと非自発的チャーンの両方を含めるべきですか？", answer: "はい。両方のタイプを別々に追跡しますが、正確性のために両方を総チャーン計算に含めてください。自発的チャーン（解約する顧客）と非自発的チャーン（支払い失敗）は異なる解決策を必要とします。" },
          { question: "ロゴチャーンと収益チャーンの違いは何ですか？", answer: "ロゴチャーンは顧客数を追跡し、収益チャーンは失われたMRRを追跡します。失った顧客の支払いが少なかった場合、収益チャーンはロゴチャーンより低くなることがあります。" },
          { question: "月次チャーンレートを減らすにはどうすればよいですか？", answer: "オンボーディングの改善（タイムトゥーバリューの短縮）、プロアクティブなカスタマーサクセス（更新前の連絡）、価格最適化（適切なプラン）、チャーンフィードバックに基づく製品改善に注力してください。" },
          { question: "SaaSにおける健全な年次チャーンレートはどのくらいですか？", answer: "年次チャーン10%未満は優秀です。10-20%は平均的です。20%を超える場合は早急な対策が必要です。" },
          { question: "顧客が少ない新製品のチャーンを計算するにはどうすればよいですか？", answer: "コホート分析を使用してください。同じ月に加入した顧客グループを追跡し、時間の経過に伴うリテンションを測定します。" },
          { question: "非自発的チャーンの原因は何ですか？", answer: "支払い失敗が非自発的チャーンの主な原因です。ダニング（自動再試行）、カード有効期限前のメール通知、複数の支払い方法を導入してください。" },
          { question: "チャーンレートは企業評価にどのように影響しますか？", answer: "劇的に影響します。チャーンが低いほど、LTVが高く、収益の予測可能性が高く、代替コストが低くなります。投資家はSaaS企業を評価する際にチャーンレートを重視します。" },
          { question: "どの業界が最も低いチャーンレートを持っていますか？", answer: "長期契約のあるエンタープライズSaaSおよびB2B企業は通常、最も低いチャーンレート（月次1-2%）を持っています。フィンテックおよびヘルスケアSaaSは多くの場合、月次チャーン3%未満です。" },
            { question: "チャーンレートはマイナスになることがありますか？", answer: "いいえ、チャーンレートは技術的にマイナスにはなりません; 失われた顧客を表します。「マイナスチャーン」は実際には純収益チャーンがマイナスである状態を指し、拡張収入がチャーンによる収入損失を上回っていることを意味します。" },
          { question: "自発的チャーンと非自発的チャーンの違いと、それぞれを減らす方法は？", answer: "自発的チャーンは顧客が能動的に解約する場合に発生します。オンボーディングの改善と製品改良で削減します。非自発的チャーンは支払い失敗から発生します。ダニングメールと自動再試行で削減します。" },
        ],
      },
    },
  },
} satisfies CalculatorConfig;

registerCalculator(config);
export default config;
