import type { Metadata } from "next";
import Link from "next/link";
import { alternateLanguages, localeUrl } from "@/lib/locale-url";
import { getTranslations } from "@/lib/getTranslations";

export async function generateMetadata(): Promise<Metadata> {
  const { t } = await getTranslations();
  return {
    title: `${t("terms.title")} - SaaStainedNumbers`,
    description: t("terms.subtitle"),
    alternates: {
      canonical: localeUrl("/terms"),
      languages: alternateLanguages("/terms"),
       },
    openGraph: {
      title: `${t("terms.title")} - SaaStainedNumbers`,
      description: t("terms.subtitle"),
      type: "website",
      images: ["/api/og?title=Terms+of+Service"],
      siteName: "SaaStainedNumbers",
       },
     };
}

export default async function TermsPage() {
  const { t } = await getTranslations();

  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <Link href="/legal" className="text-sm text-brand-600 dark:text-brand-400 hover:text-brand-700 dark:hover:text-brand-300 mb-4 inline-block">
        ← {t("footer.legal")}
      </Link>
      <h1 className="font-heading text-3xl font-bold text-gray-900 dark:text-gray-100">
        {t("terms.heading")}
      </h1>
      <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
        Last updated: May 26, 2026
      </p>

      <hr className="my-8 border-gray-200 dark:border-gray-700" />

      <div className="prose prose-gray dark:prose-invert max-w-none">
        <h2>Acceptance of Terms</h2>
        <p>
          By using SaaStainedNumbers, you agree to these Terms of Service. If you do not agree,
          please do not use the website.
        </p>

        <h2>Description of Service</h2>
        <p>
          SaaStainedNumbers provides free, browser-based financial and business calculators for
          informational and educational purposes. All calculations are performed client-side. No
          account is required to use the calculators.
        </p>

        <h2>User Responsibilities</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use SaaStainedNumbers for any unlawful purpose or in violation of any applicable law.</li>
          <li>Scrape, crawl, or otherwise automatically extract data from the website.</li>
          <li>Interfere with the operation of the website or attempt to circumvent its security.</li>
          <li>Misrepresent calculator results as your own or as professional advice.</li>
          <li>Use the website in a way that could damage, disable, or impair our infrastructure.</li>
        </ul>

        <h2>Intellectual Property</h2>
        <p>
          The design, brand assets, and original text content on SaaStainedNumbers are the
          property of SaaStainedNumbers unless otherwise noted. Calculator logic and formulas
          are based on standard mathematical and financial concepts and are not proprietary.
          Calculator results generated by you are yours to use freely.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, SaaStainedNumbers and its operators shall not
          be liable for any direct, indirect, incidental, consequential, or punitive damages
          arising from or related to your use of the website, including but not limited to
          financial losses, business decisions, or lost profits based on calculator results or
          content.
        </p>

        <h2>Governing Law</h2>
        <p>
          These terms are governed by the laws of Ontario, Canada.
        </p>

        <h2>Changes to Terms</h2>
        <p>
          We may update these terms from time to time. Changes will be posted on this page.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms? Contact us at{" "}
          <a href="mailto:legal@saastainednumbers.com" className="text-brand-600 dark:text-brand-400 hover:underline">
            legal@saastainednumbers.com
          </a>.
        </p>
      </div>
    </div>
  );
}
