import { calculateActivationRate } from "@/calculators/engine/activation-rate";
import { calculateACV } from "@/calculators/engine/acv";
import { calculateAffiliateIncome } from "@/calculators/engine/affiliate-income";
import { calculateAIFineTuningCost } from "@/calculators/engine/ai-fine-tuning-cost";
import { calculateAIImageCost } from "@/calculators/engine/ai-image-cost";
import { calculateAIModelComparison } from "@/calculators/engine/ai-model-comparison";
import { calculateAmazonFBA } from "@/calculators/engine/amazon-fba";
import { calculateARPU } from "@/calculators/engine/arpu";
import { calculateBloggingIncome } from "@/calculators/engine/blogging-income";
import { calculateBreakEven } from "@/calculators/engine/break-even";
import { calculateBurnRate, calculateRunway } from "@/calculators/engine/burn-rate";
import { calculateBusinessValuation } from "@/calculators/engine/business-valuation";
import { calculateCAC } from "@/calculators/engine/cac";
import { calculateCACLTVRatio } from "@/calculators/engine/cac-ltv-ratio";
import { calculateCACPaybackPeriod } from "@/calculators/engine/cac-payback-period-enhanced";
import { calculateCashRunway } from "@/calculators/engine/cash-runway";
import { calculateChatGPTAPICost } from "@/calculators/engine/chatgpt-api-cost";
import { calculateChurn } from "@/calculators/engine/churn";
import { calculateClaudeAPICost } from "@/calculators/engine/claude-api-cost";
import { calculateCohortAnalysis } from "@/calculators/engine/cohort-analysis";
import { calculateContractorVsEmployee } from "@/calculators/engine/contractor-vs-employee";
import { calculateContributionMargin } from "@/calculators/engine/contribution-margin";
import { calculateCreditCardPayoff } from "@/calculators/engine/credit-card-payoff";
import { calculateCustomerEngagementScore } from "@/calculators/engine/customer-engagement-score";
import { calculateCustomerHealthScore } from "@/calculators/engine/customer-health-score";
import { calculateDebtPayoff } from "@/calculators/engine/debt-payoff";
import { calculateDividendIncome } from "@/calculators/engine/dividend-income";
import { calculateDropshippingMargin } from "@/calculators/engine/dropshipping-margin";
import { calculateEmergencyFund } from "@/calculators/engine/emergency-fund";
import { calculateEmployeeCost } from "@/calculators/engine/employee-cost";
import { calculateEtsyProfit } from "@/calculators/engine/etsy-profit";
import { calculateExpansionRevenueRate } from "@/calculators/engine/expansion-revenue-rate";
import { calculateFeatureAdoptionRate } from "@/calculators/engine/feature-adoption-rate";
import { calculateFIRE } from "@/calculators/engine/fire";
import { calculateFreelanceRate } from "@/calculators/engine/freelance-rate";
import { calculateGeminiAPICost } from "@/calculators/engine/gemini-api-cost";
import { calculateGigWorkerTakeHome } from "@/calculators/engine/gig-worker-take-home";
import { calculateGrokAPICost } from "@/calculators/engine/grok-api-cost";
import { calculateGrossMargin } from "@/calculators/engine/gross-margin";
import { calculateInvestmentReturns } from "@/calculators/engine/investment-returns";
import { calculateLeadConversionRate } from "@/calculators/engine/lead-conversion-rate";
import { calculateLTV } from "@/calculators/engine/ltv";
import { calculateMagicNumber } from "@/calculators/engine/magic-number";
import { calculateMortgageAffordability } from "@/calculators/engine/mortgage-affordability";
import { calculateMRR } from "@/calculators/engine/mrr";
import { calculateMRRGrowthRate } from "@/calculators/engine/mrr-growth-rate";
import { calculateNetCashFlow } from "@/calculators/engine/net-cash-flow";
import { calculateNewsletterRevenue } from "@/calculators/engine/newsletter-revenue";
import { calculateNetPromoterScore } from "@/calculators/engine/nps";
import { calculateNRR } from "@/calculators/engine/nrr";
import { calculateOperatingMargin } from "@/calculators/engine/operating-margin";
import { calculatePaybackPeriod } from "@/calculators/engine/payback-period";
import { calculatePerplexityAPICost } from "@/calculators/engine/perplexity-api-cost";
import { calculatePodcastRevenue } from "@/calculators/engine/podcast-revenue";
import { calculatePricingStrategy } from "@/calculators/engine/pricing-strategy";
import { calculatePrintOnDemandProfit } from "@/calculators/engine/print-on-demand-profit";
import { calculateQuickRatio } from "@/calculators/engine/quick-ratio";
import { calculateRentVsBuy } from "@/calculators/engine/rent-vs-buy";
import { calculateRetire401k } from "@/calculators/engine/retire-401k";
import { calculateRevenuePerEmployee } from "@/calculators/engine/revenue-per-employee";
import { calculateRevenuePerUserTrend } from "@/calculators/engine/revenue-per-user-trend";
import { calculateROI } from "@/calculators/engine/roi";
import { calculateRuleOf40 } from "@/calculators/engine/rule-of-40";
import { calculateSaaSCapitalEfficiency } from "@/calculators/engine/saas-capital-efficiency";
import { calculateSaaSQuickRatio } from "@/calculators/engine/saas-quick-ratio";
import { calculateSavingsRate } from "@/calculators/engine/savings-rate";
import { calculateSideIncomeTax } from "@/calculators/engine/side-income-tax";
import { calculateStudentLoanPayoff } from "@/calculators/engine/student-loan-payoff";
import { calculateSubscriptionContentRevenue } from "@/calculators/engine/subscription-content-revenue";
import { calculateTikTokCreatorFund } from "@/calculators/engine/tiktok-creator-fund";
import { calculateTimeToValue } from "@/calculators/engine/time-to-value";
import { calculateTrialToPaid } from "@/calculators/engine/trial-to-paid";
import { calculateTwitchRevenue } from "@/calculators/engine/twitch-revenue";
import { calculateUnitEconomicsDashboard } from "@/calculators/engine/unit-economics-dashboard";
import { calculateYouTubeAdRevenue } from "@/calculators/engine/youtube-ad-revenue";

export const engines: Record<string, (params: Record<string, number>) => Record<string, number | string>> = {
  "activation-rate-calculator": (p) => { const r = calculateActivationRate({ signups: p.signups, activated: p.activated }); return { activationRate: r.activationRate, notActivated: r.notActivated }; },
  "acv-calculator": (p) => { const r = calculateACV({ totalContractValue: p.totalContractValue, contractDurationYears: p.contractDurationYears }); return { acv: r.acv, tcv: r.tcv }; },
  "affiliate-income-calculator": (p) => { const r = calculateAffiliateIncome({ monthlyVisitors: p.monthlyVisitors, clickThroughRate: p.clickThroughRate, conversionRate: p.conversionRate, averageCommission: p.averageCommission, cookieDurationDays: p.cookieDurationDays }); return { monthlyClicks: r.monthlyClicks, monthlyConversions: r.monthlyConversions, monthlyRevenue: r.monthlyRevenue, annualRevenue: r.annualRevenue, revenuePerVisitor: r.revenuePerVisitor, revenuePerClick: r.revenuePerClick }; },
  "ai-fine-tuning-cost-calculator": (p) => { const r = calculateAIFineTuningCost({ trainingTokens: p.trainingTokens, trainingCostPerMillion: p.trainingCostPerMillion, monthlyInferenceTokens: p.monthlyInferenceTokens, inferenceInputPricePerMillion: p.inferenceInputPricePerMillion, inferenceOutputPricePerMillion: p.inferenceOutputPricePerMillion, epochs: p.epochs }); return { trainingCost: r.trainingCost, monthlyInferenceCost: r.monthlyInferenceCost, annualInferenceCost: r.annualInferenceCost, totalFirstYearCost: r.totalFirstYearCost, costPerInferenceCall: r.costPerInferenceCall }; },
  "ai-image-cost-calculator": (p) => { const r = calculateAIImageCost({ imagesPerMonth: p.imagesPerMonth, costPerImage: p.costPerImage }); return { monthlyCost: r.monthlyCost, annualCost: r.annualCost, costPerImage: r.costPerImage }; },
  "ai-model-comparison-calculator": (p) => { const r = calculateAIModelComparison({ claudeInputTokens: p.claudeInputTokens, claudeOutputTokens: p.claudeOutputTokens, claudeCallsPerDay: p.claudeCallsPerDay, gptInputTokens: p.gptInputTokens, gptOutputTokens: p.gptOutputTokens, gptCallsPerDay: p.gptCallsPerDay, geminiInputTokens: p.geminiInputTokens, geminiOutputTokens: p.geminiOutputTokens, geminiCallsPerDay: p.geminiCallsPerDay }); return { claudeMonthlyCost: r.claudeMonthlyCost, gptMonthlyCost: r.gptMonthlyCost, geminiMonthlyCost: r.geminiMonthlyCost, cheapest: r.cheapest, savingsVsAvg: r.savingsVsAvg }; },
  "amazon-fba-calculator": (p) => { const r = calculateAmazonFBA({ itemPrice: p.itemPrice, costOfGoods: p.costOfGoods, referralFeePercent: p.referralFeePercent, fbaFulfillmentFee: p.fbaFulfillmentFee, monthlyStorageFee: p.monthlyStorageFee, advertisingCostPerUnit: p.advertisingCostPerUnit, unitsSoldPerMonth: p.unitsSoldPerMonth }); return { monthlyRevenue: r.monthlyRevenue, monthlyCostOfGoods: r.monthlyCostOfGoods, monthlyReferralFees: r.monthlyReferralFees, monthlyFulfillmentFees: r.monthlyFulfillmentFees, monthlyStorageFees: r.monthlyStorageFees, monthlyAdvertisingCost: r.monthlyAdvertisingCost, monthlyTotalFees: r.monthlyTotalFees, monthlyTotalCosts: r.monthlyTotalCosts, monthlyProfit: r.monthlyProfit, profitMargin: r.profitMargin, profitPerUnit: r.profitPerUnit }; },
  "arpu-calculator": (p) => { const r = calculateARPU({ mrr: p.mrr, totalCustomers: p.totalCustomers }); return { arpu: r.arpu }; },
  "blogging-income-calculator": (p) => { const r = calculateBloggingIncome({ monthlyPageviews: p.monthlyPageviews, adRpm: p.adRpm, affiliateRevenuePerMonth: p.affiliateRevenuePerMonth, sponsoredPostRevenuePerMonth: p.sponsoredPostRevenuePerMonth, digitalProductRevenue: p.digitalProductRevenue }); return { monthlyAdRevenue: r.monthlyAdRevenue, monthlyAffiliateRevenue: r.monthlyAffiliateRevenue, monthlySponsoredRevenue: r.monthlySponsoredRevenue, monthlyDigitalProductRevenue: r.monthlyDigitalProductRevenue, monthlyTotalRevenue: r.monthlyTotalRevenue, annualRevenue: r.annualRevenue, revenuePerThousandPageviews: r.revenuePerThousandPageviews }; },
  "break-even-calculator": (p) => { const r = calculateBreakEven({ fixedCosts: p.fixedCosts, variableCostPerUnit: p.variableCostPerUnit, pricePerUnit: p.pricePerUnit }); return { breakEvenUnits: r.breakEvenUnits, breakEvenRevenue: r.breakEvenRevenue, contributionMargin: r.contributionMargin, contributionMarginPercent: r.contributionMarginPercent }; },
  "burn-rate-calculator": (p) => { const r = p.cashReserves > 0 ? calculateRunway({ monthlyExpenses: p.monthlyExpenses, monthlyRevenue: p.monthlyRevenue, cashReserves: p.cashReserves }) : { ...calculateBurnRate({ monthlyExpenses: p.monthlyExpenses, monthlyRevenue: p.monthlyRevenue }), runwayMonths: 0, cashReserves: 0 }; return { netBurnRate: r.netBurnRate, grossBurnRate: r.grossBurnRate, runwayMonths: r.runwayMonths }; },
  "business-valuation-calculator": (p) => { const r = calculateBusinessValuation({ annualRevenue: p.annualRevenue, ebitdaMargin: p.ebitdaMargin, revenueMultiple: p.revenueMultiple, ebitdaMultiple: p.ebitdaMultiple, growthRate: p.growthRate }); return { revenueBasedValue: r.revenueBasedValue, ebitdaBasedValue: r.ebitdaBasedValue, blendedValue: r.blendedValue, ebitda: r.ebitda }; },
  "cac-calculator": (p) => { const r = calculateCAC({ salesCost: p.salesCost, marketingCost: p.marketingCost, newCustomers: p.newCustomers }); return { cac: r.cac }; },
  "cac-ltv-ratio-calculator": (p) => { const r = calculateCACLTVRatio({ ltv: p.ltv, cac: p.cac }); return { ratio: r.ratio }; },
  "cac-payback-period-enhanced-calculator": (p) => { const r = calculateCACPaybackPeriod({ cac: p.cac, arpu: p.arpu, grossMargin: p.grossMargin }); return { paybackMonths: r.paybackMonths, paybackDays: r.paybackDays, grossProfitPerMonth: r.grossProfitPerMonth }; },
  "cash-runway-calculator": (p) => { const r = calculateCashRunway({ currentCash: p.currentCash, monthlyRevenue: p.monthlyRevenue, monthlyExpenses: p.monthlyExpenses, monthlyGrowthRate: p.monthlyGrowthRate }); return { grossBurn: r.grossBurn, netBurn: r.netBurn, runwayMonths: r.runwayMonths, revenueRunwayMonths: r.revenueRunwayMonths }; },
  "chatgpt-api-cost-calculator": (p) => { const r = calculateChatGPTAPICost({ inputTokens: p.inputTokens, outputTokens: p.outputTokens, callsPerDay: p.callsPerDay, inputPricePerMillion: p.inputPricePerMillion, outputPricePerMillion: p.outputPricePerMillion }); return { costPerCall: r.costPerCall, costPerDay: r.costPerDay, costPerMonth: r.costPerMonth, costPerYear: r.costPerYear }; },
  "churn-calculator": (p) => { const r = calculateChurn({ customersStart: p.customersStart, customersEnd: p.customersEnd, lostCustomers: p.lostCustomers }); return { monthlyChurnPct: r.monthlyChurnPct, annualChurnPct: r.annualChurnPct, retainedCustomers: r.retainedCustomers }; },
  "claude-api-cost-calculator": (p) => { const r = calculateClaudeAPICost({ inputTokens: p.inputTokens, outputTokens: p.outputTokens, callsPerDay: p.callsPerDay, inputPricePerMillion: p.inputPricePerMillion, outputPricePerMillion: p.outputPricePerMillion }); return { costPerCall: r.costPerCall, costPerDay: r.costPerDay, costPerMonth: r.costPerMonth, costPerYear: r.costPerYear }; },
  "cohort-analysis-calculator": (p) => { const r = calculateCohortAnalysis({ initialCohortSize: p.initialCohortSize, retentionRates: [p.month1Retention, p.month2Retention, p.month3Retention], months: 3 }); return { month1Retained: r.retainedUsers[0] ?? 0, month2Retained: r.retainedUsers[1] ?? 0, month3Retained: r.retainedUsers[2] ?? 0, averageRetention: r.averageRetention }; },
  "contractor-vs-employee-calculator": (p) => { const r = calculateContractorVsEmployee({ contractorRate: p.contractorRate, contractorHoursPerYear: p.contractorHoursPerYear, employeeSalary: p.employeeSalary, employeeBonusPercent: p.employeeBonusPercent, employeeBenefitsPercent: p.employeeBenefitsPercent, employeePayrollTaxPercent: p.employeePayrollTaxPercent, employeeEquipmentCost: p.employeeEquipmentCost, employeeOfficeCost: p.employeeOfficeCost }); return { contractorAnnualCost: r.contractorAnnualCost, employeeAnnualCost: r.employeeAnnualCost, difference: r.difference, contractorCheaperBy: r.contractorCheaperBy, percentDiff: r.percentDiff }; },
  "contribution-margin-calculator": (p) => { const r = calculateContributionMargin({ revenue: p.revenue, variableCosts: p.variableCosts }); return { contributionMargin: r.contributionMargin, contributionMarginPct: r.contributionMarginPct }; },
  "credit-card-payoff-calculator": (p) => { const r = calculateCreditCardPayoff({ totalBalance: p.totalBalance, interestRate: p.interestRate, monthlyPayment: p.monthlyPayment }); return { monthsToPayoff: r.monthsToPayoff, yearsToPayoff: r.yearsToPayoff, totalInterestPaid: r.totalInterestPaid, totalPaid: r.totalPaid }; },
  "customer-engagement-score-calculator": (p) => { const r = calculateCustomerEngagementScore({ dailyActiveUsers: p.dailyActiveUsers, monthlyActiveUsers: p.monthlyActiveUsers, sessionsPerUserPerMonth: p.sessionsPerUserPerMonth, avgSessionDurationMinutes: p.avgSessionDurationMinutes, featureAdoptionRate: p.featureAdoptionRate }); return { dauMauRatio: r.dauMauRatio, engagementScore: r.engagementScore, engagementCategory: r.engagementCategory, totalMonthlySessions: r.totalMonthlySessions }; },
  "customer-health-score-calculator": (p) => { const r = calculateCustomerHealthScore({ nps: p.nps, productUsageScore: p.productUsageScore, supportTickets: p.supportTickets, daysSinceLastLogin: p.daysSinceLastLogin }); return { healthScore: r.healthScore, healthCategory: r.healthCategory }; },
  "debt-payoff-calculator": (p) => { const r = calculateDebtPayoff({ totalDebt: p.totalDebt, interestRate: p.interestRate, monthlyPayment: p.monthlyPayment }); return { monthsToPayoff: r.monthsToPayoff, yearsToPayoff: r.yearsToPayoff, totalInterestPaid: r.totalInterestPaid, totalPaid: r.totalPaid }; },
  "dividend-income-calculator": (p) => { const r = calculateDividendIncome({ initialInvestment: p.initialInvestment, monthlyContribution: p.monthlyContribution, dividendYield: p.dividendYield, dividendGrowthRate: p.dividendGrowthRate, years: p.years }); return { totalInvested: r.totalInvested, portfolioValue: r.portfolioValue, annualDividendIncome: r.annualDividendIncome, monthlyDividendIncome: r.monthlyDividendIncome, dividendYield: r.dividendYield }; },
  "dropshipping-margin-calculator": (p) => { const r = calculateDropshippingMargin({ productPrice: p.productPrice, supplierCost: p.supplierCost, shippingCost: p.shippingCost, platformFeePercent: p.platformFeePercent, advertisingCostPerUnit: p.advertisingCostPerUnit, unitsSoldPerMonth: p.unitsSoldPerMonth, returnRate: p.returnRate }); return { monthlyRevenue: r.monthlyRevenue, monthlyCOGS: r.monthlyCOGS, monthlyShipping: r.monthlyShipping, monthlyPlatformFees: r.monthlyPlatformFees, monthlyAdCost: r.monthlyAdCost, monthlyReturnCost: r.monthlyReturnCost, monthlyTotalCosts: r.monthlyTotalCosts, monthlyProfit: r.monthlyProfit, profitMargin: r.profitMargin, profitPerUnit: r.profitPerUnit }; },
  "emergency-fund-calculator": (p) => { const r = calculateEmergencyFund({ monthlyExpenses: p.monthlyExpenses, currentSavings: p.currentSavings, monthlySavings: p.monthlySavings, targetMonths: p.targetMonths }); return { targetAmount: r.targetAmount, currentCoverageMonths: r.currentCoverageMonths, shortfall: r.shortfall, monthsToGoal: r.monthsToGoal }; },
  "employee-cost-calculator": (p) => { const r = calculateEmployeeCost({ baseSalary: p.baseSalary, bonusPercent: p.bonusPercent, payrollTaxPercent: p.payrollTaxPercent, benefitsPercent: p.benefitsPercent, equipmentCost: p.equipmentCost, officeSpaceCost: p.officeSpaceCost, headcount: p.headcount }); return { totalCostPerEmployee: r.totalCostPerEmployee, totalCostAllEmployees: r.totalCostAllEmployees, salaryBurdenPercent: r.salaryBurdenPercent, monthlyCostPerEmployee: r.monthlyCostPerEmployee, annualBenefitsCost: r.annualBenefitsCost, annualPayrollTaxCost: r.annualPayrollTaxCost }; },
  "etsy-profit-calculator": (p) => { const r = calculateEtsyProfit({ itemPrice: p.itemPrice, costOfGoods: p.costOfGoods, shippingCost: p.shippingCost, listingFee: p.listingFee, transactionFeePercent: p.transactionFeePercent, paymentFeePercent: p.paymentFeePercent, paymentFixedFee: p.paymentFixedFee, quantitySold: p.quantitySold }); return { revenue: r.revenue, totalCostOfGoods: r.totalCostOfGoods, totalShipping: r.totalShipping, totalListingFees: r.totalListingFees, totalTransactionFees: r.totalTransactionFees, totalPaymentFees: r.totalPaymentFees, totalFees: r.totalFees, totalCosts: r.totalCosts, profit: r.profit, profitMargin: r.profitMargin, profitPerItem: r.profitPerItem }; },
  "expansion-revenue-rate-calculator": (p) => { const r = calculateExpansionRevenueRate({ beginningMrr: p.beginningMrr, expansionMrr: p.expansionMrr }); return { expansionRevenueRate: r.expansionRevenueRate }; },
  "feature-adoption-rate-calculator": (p) => { const r = calculateFeatureAdoptionRate({ totalUsers: p.totalUsers, usersUsingFeature: p.usersUsingFeature, targetAdoptionRate: p.targetAdoptionRate }); return { adoptionRate: r.adoptionRate, gapToTarget: r.gapToTarget, usersNeeded: r.usersNeeded, status: r.status }; },
  "fire-calculator": (p) => { const r = calculateFIRE({ currentSavings: p.currentSavings, monthlyContribution: p.monthlyContribution, annualReturn: p.annualReturn, desiredMonthlyWithdrawal: p.desiredMonthlyWithdrawal, currentAge: p.currentAge, retirementAge: p.retirementAge }); return { savingsAtRetirement: r.savingsAtRetirement, fireNumber: r.fireNumber, yearsToFI: r.yearsToFI, ageAtFI: r.ageAtFI }; },
  "freelance-rate-calculator": (p) => { const r = calculateFreelanceRate({ desiredIncome: p.desiredIncome, billableHoursPerWeek: p.billableHoursPerWeek, weeksPerYear: p.weeksPerYear, expenses: p.expenses, taxRate: p.taxRate }); return { hourlyRate: r.hourlyRate, monthlyRevenue: r.monthlyRevenue, annualRevenue: r.annualRevenue, monthlyTakeHome: r.monthlyTakeHome, annualTakeHome: r.annualTakeHome }; },
  "gemini-api-cost-calculator": (p) => { const r = calculateGeminiAPICost({ inputTokens: p.inputTokens, outputTokens: p.outputTokens, callsPerDay: p.callsPerDay, inputPricePerMillion: p.inputPricePerMillion, outputPricePerMillion: p.outputPricePerMillion }); return { costPerCall: r.costPerCall, costPerDay: r.costPerDay, costPerMonth: r.costPerMonth, costPerYear: r.costPerYear }; },
  "gig-worker-take-home-calculator": (p) => { const r = calculateGigWorkerTakeHome({ hoursPerWeek: p.hoursPerWeek, hourlyEarnings: p.hourlyEarnings, weeklyExpenses: p.weeklyExpenses, taxRate: p.taxRate }); return { grossWeeklyIncome: r.grossWeeklyIncome, weeklyExpenses: r.weeklyExpenses, netWeeklyIncome: r.netWeeklyIncome, netMonthlyIncome: r.netMonthlyIncome, netAnnualIncome: r.netAnnualIncome, effectiveHourlyRate: r.effectiveHourlyRate }; },
  "grok-api-cost-calculator": (p) => { const r = calculateGrokAPICost({ inputTokens: p.inputTokens, outputTokens: p.outputTokens, callsPerDay: p.callsPerDay, inputPricePerMillion: p.inputPricePerMillion, outputPricePerMillion: p.outputPricePerMillion }); return { costPerCall: r.costPerCall, costPerDay: r.costPerDay, costPerMonth: r.costPerMonth, costPerYear: r.costPerYear }; },
  "gross-margin-calculator": (p) => { const r = calculateGrossMargin({ revenue: p.revenue, cogs: p.cogs }); return { grossMargin: r.grossMargin, grossProfit: r.grossProfit, cogsPercentage: r.cogsPercentage }; },
  "investment-returns-calculator": (p) => { const r = calculateInvestmentReturns({ initialInvestment: p.initialInvestment, monthlyContribution: p.monthlyContribution, annualReturn: p.annualReturn, years: p.years }); return { totalContributions: r.totalContributions, totalValue: r.totalValue, totalEarnings: r.totalEarnings, annualizedReturn: r.annualizedReturn }; },
  "lead-conversion-rate-calculator": (p) => { const r = calculateLeadConversionRate({ leads: p.leads, customers: p.customers }); return { conversionRate: r.conversionRate, lostLeads: r.lostLeads }; },
  "ltv-calculator": (p) => { const r = calculateLTV({ arpu: p.arpu, grossMargin: p.grossMargin, churnRate: p.churnRate }); return { ltv: r.ltv, ltvCacRatio: r.ltvCacRatio }; },
  "magic-number-calculator": (p) => { const r = calculateMagicNumber({ newArr: p.newArr, salesMarketingSpend: p.salesMarketingSpend }); return { magicNumber: r.magicNumber }; },
  "mortgage-affordability-calculator": (p) => { const r = calculateMortgageAffordability({ annualIncome: p.annualIncome, monthlyDebtPayments: p.monthlyDebtPayments, downPayment: p.downPayment, interestRate: p.interestRate, loanTermYears: p.loanTermYears, propertyTaxRate: p.propertyTaxRate, insuranceMonthly: p.insuranceMonthly }); return { maxHomePrice: r.maxHomePrice, monthlyPayment: r.monthlyPayment, downPaymentPercent: r.downPaymentPercent, debtToIncomeRatio: r.debtToIncomeRatio, loanAmount: r.loanAmount, totalInterestPaid: r.totalInterestPaid }; },
  "mrr-calculator": (p) => { const r = calculateMRR({ customers: p.customers, arpu: p.arpu }); return { mrr: r.mrr, arr: r.arr }; },
  "mrr-growth-rate-calculator": (p) => { const r = calculateMRRGrowthRate({ previousMrr: p.previousMrr, currentMrr: p.currentMrr }); return { growthRate: r.growthRate, mrrChange: r.mrrChange }; },
  "net-cash-flow-calculator": (p) => { const r = calculateNetCashFlow({ cashIn: p.cashIn, cashOut: p.cashOut }); return { netCashFlow: r.netCashFlow, burnRate: r.burnRate, isPositive: r.isPositive ? "Yes" : "No" }; },
  "newsletter-revenue-calculator": (p) => { const r = calculateNewsletterRevenue({ subscribers: p.subscribers, freeToPaidConversionRate: p.freeToPaidConversionRate, monthlyPrice: p.monthlyPrice, sponsorshipCpm: p.sponsorshipCpm, sponsorshipEmailsPerMonth: p.sponsorshipEmailsPerMonth, openRate: p.openRate }); return { paidSubscribers: r.paidSubscribers, monthlySubscriptionRevenue: r.monthlySubscriptionRevenue, monthlySponsorshipRevenue: r.monthlySponsorshipRevenue, monthlyTotalRevenue: r.monthlyTotalRevenue, annualRevenue: r.annualRevenue, revenuePerSubscriber: r.revenuePerSubscriber }; },
  "nps-calculator": (p) => { const r = calculateNetPromoterScore({ promoters: p.promoters, passives: p.passives, detractors: p.detractors }); return { nps: r.nps, totalResponses: r.totalResponses, promoterPct: r.promoterPct }; },
  "nrr-calculator": (p) => { const r = calculateNRR({ startMrr: p.startMrr, expansionMrr: p.expansionMrr, churnedMrr: p.churnedMrr, contractionMrr: p.contractionMrr }); return { nrr: r.nrr, netRetentionRate: r.netRetentionRate, grossRetentionRate: r.grossRetentionRate }; },
  "operating-margin-calculator": (p) => { const r = calculateOperatingMargin({ operatingIncome: p.operatingIncome, revenue: p.revenue }); return { operatingMargin: r.operatingMargin }; },
  "payback-period-calculator": (p) => { const r = calculatePaybackPeriod({ cac: p.cac, arpu: p.arpu, grossMargin: p.grossMargin }); return { paybackPeriodMonths: r.paybackPeriodMonths, yearlyProfit: r.yearlyProfit }; },
  "perplexity-api-cost-calculator": (p) => { const r = calculatePerplexityAPICost({ inputTokens: p.inputTokens, outputTokens: p.outputTokens, callsPerDay: p.callsPerDay, inputPricePerMillion: p.inputPricePerMillion, outputPricePerMillion: p.outputPricePerMillion }); return { costPerCall: r.costPerCall, costPerDay: r.costPerDay, costPerMonth: r.costPerMonth, costPerYear: r.costPerYear }; },
  "podcast-revenue-calculator": (p) => { const r = calculatePodcastRevenue({ downloadsPerEpisode: p.downloadsPerEpisode, episodesPerMonth: p.episodesPerMonth, cpm: p.cpm, sponsorshipRate: p.sponsorshipRate, sponsorsPerEpisode: p.sponsorsPerEpisode }); return { monthlyAdRevenue: r.monthlyAdRevenue, monthlySponsorshipRevenue: r.monthlySponsorshipRevenue, monthlyTotalRevenue: r.monthlyTotalRevenue, annualRevenue: r.annualRevenue, revenuePerThousandDownloads: r.revenuePerThousandDownloads }; },
  "pricing-strategy-calculator": (p) => { const r = calculatePricingStrategy({ costPerUnit: p.costPerUnit, desiredMarginPercent: p.desiredMarginPercent, competitorPrice: p.competitorPrice, customerPerceivedValue: p.customerPerceivedValue }); return { costPlusPrice: r.costPlusPrice, targetMarginPrice: r.targetMarginPrice, competitivePricePosition: r.competitivePricePosition, valueBasedPrice: r.valueBasedPrice, recommendedPrice: r.recommendedPrice, recommendedMargin: r.recommendedMargin }; },
  "print-on-demand-profit-calculator": (p) => { const r = calculatePrintOnDemandProfit({ itemPrice: p.itemPrice, baseProductCost: p.baseProductCost, printCost: p.printCost, platformFee: p.platformFee, shippingCost: p.shippingCost, unitsSoldPerMonth: p.unitsSoldPerMonth }); return { monthlyRevenue: r.monthlyRevenue, monthlyCOGS: r.monthlyCOGS, monthlyFees: r.monthlyFees, monthlyShipping: r.monthlyShipping, monthlyProfit: r.monthlyProfit, profitMargin: r.profitMargin, profitPerUnit: r.profitPerUnit }; },
  "quick-ratio-calculator": (p) => { const r = calculateQuickRatio({ newMrr: p.newMrr, expansionMrr: p.expansionMrr, churnedMrr: p.churnedMrr, contractionMrr: p.contractionMrr }); return { quickRatio: r.quickRatio, growthMrr: r.growthMrr, lostMrr: r.lostMrr }; },
  "rent-vs-buy-calculator": (p) => { const r = calculateRentVsBuy({ homePrice: p.homePrice, downPayment: p.downPayment, interestRate: p.interestRate, loanTermYears: p.loanTermYears, propertyTaxRate: p.propertyTaxRate, homeInsuranceMonthly: p.homeInsuranceMonthly, maintenanceRate: p.maintenanceRate, hoaMonthly: p.hoaMonthly, monthlyRent: p.monthlyRent, rentInsuranceMonthly: p.rentInsuranceMonthly, yearsPlanned: p.yearsPlanned, investmentReturn: p.investmentReturn, closingCostPercent: p.closingCostPercent, sellingCostPercent: p.sellingCostPercent }); return { totalRentCost: r.totalRentCost, totalBuyCost: r.totalBuyCost, netEquity: r.netEquity, buyAdvantage: r.buyAdvantage, buyBetter: r.buyBetter ? "Yes" : "No", monthlyBuyPayment: r.monthlyBuyPayment }; },
  "retire-401k-calculator": (p) => { const r = calculateRetire401k({ currentBalance: p.currentBalance, annualContribution: p.annualContribution, employerMatchPercent: p.employerMatchPercent, employerMatchCap: p.employerMatchCap, annualReturn: p.annualReturn, currentAge: p.currentAge, retirementAge: p.retirementAge }); return { balanceAtRetirement: r.balanceAtRetirement, totalContributions: r.totalContributions, totalEmployerMatch: r.totalEmployerMatch, totalEarnings: r.totalEarnings, annualIncomeAtRetirement: r.annualIncomeAtRetirement }; },
  "revenue-per-employee-calculator": (p) => { const r = calculateRevenuePerEmployee({ totalRevenue: p.totalRevenue, headcount: p.headcount }); return { revenuePerEmployee: r.revenuePerEmployee }; },
  "revenue-per-user-trend-calculator": (p) => { const r = calculateRevenuePerUserTrend({ monthlyRevenue: [p.prevMonthRevenue, p.currentMonthRevenue], monthlyUsers: [p.prevMonthUsers, p.currentMonthUsers] }); return { currentArpu: r.currentArpu, prevArpu: r.prevArpu, arpuGrowth: r.arpuGrowth, trend: r.trend }; },
  "roi-calculator": (p) => { const r = calculateROI({ initialInvestment: p.initialInvestment, finalValue: p.finalValue, years: p.years }); return { totalGain: r.totalGain, roiPercent: r.roiPercent, annualizedROI: r.annualizedROI }; },
  "rule-of-40-calculator": (p) => { const r = calculateRuleOf40({ revenueGrowthRate: p.revenueGrowthRate, profitMargin: p.profitMargin }); return { ruleOf40Score: r.ruleOf40Score, meetsThreshold: r.meetsThreshold ? "Yes" : "No" }; },
  "saas-capital-efficiency-calculator": (p) => { const r = calculateSaaSCapitalEfficiency({ totalRaised: p.totalRaised, arr: p.arr, arrGrowthLastYear: p.arrGrowthLastYear }); return { efficiencyRatio: r.efficiencyRatio, category: r.category, arrPerDollarRaised: r.arrPerDollarRaised }; },
  "saas-quick-ratio-calculator": (p) => { const r = calculateSaaSQuickRatio({ newMRR: p.newMRR, expansionMRR: p.expansionMRR, churnedMRR: p.churnedMRR, contractionMRR: p.contractionMRR }); return { quickRatio: r.quickRatio, isHealthy: r.isHealthy ? "Yes" : "No", category: r.category }; },
  "savings-rate-calculator": (p) => { const r = calculateSavingsRate({ monthlyIncome: p.monthlyIncome, monthlyExpenses: p.monthlyExpenses, currentSavings: p.currentSavings, targetSavings: p.targetSavings }); return { monthlySavings: r.monthlySavings, savingsRate: r.savingsRate, monthsToTarget: r.monthsToTarget, yearsToTarget: r.yearsToTarget }; },
  "side-income-tax-calculator": (p) => { const r = calculateSideIncomeTax({ sideIncome: p.sideIncome, employmentIncome: p.employmentIncome, filingStatus: String(p.filingStatus), state: String(p.state), expenses: p.expenses }); return { taxableSideIncome: r.taxableSideIncome, selfEmploymentTax: r.selfEmploymentTax, estimatedFederalTax: r.estimatedFederalTax, estimatedStateTax: r.estimatedStateTax, totalAdditionalTax: r.totalAdditionalTax, effectiveTaxRate: r.effectiveTaxRate, afterTaxSideIncome: r.afterTaxSideIncome }; },
  "student-loan-payoff-calculator": (p) => { const r = calculateStudentLoanPayoff({ totalLoan: p.totalLoan, interestRate: p.interestRate, monthlyPayment: p.monthlyPayment }); return { monthsToPayoff: r.monthsToPayoff, yearsToPayoff: r.yearsToPayoff, totalInterestPaid: r.totalInterestPaid, totalPaid: r.totalPaid }; },
  "subscription-content-revenue-calculator": (p) => { const r = calculateSubscriptionContentRevenue({ freeFollowers: p.freeFollowers, conversionRate: p.conversionRate, monthlyPrice: p.monthlyPrice, payPerViewRevenue: p.payPerViewRevenue, tipsPerMonth: p.tipsPerMonth }); return { paidSubscribers: r.paidSubscribers, monthlySubRevenue: r.monthlySubRevenue, monthlyPPVRevenue: r.monthlyPPVRevenue, monthlyTipsRevenue: r.monthlyTipsRevenue, monthlyTotal: r.monthlyTotal, annualRevenue: r.annualRevenue }; },
  "tiktok-creator-fund-calculator": (p) => { const r = calculateTikTokCreatorFund({ monthlyViews: p.monthlyViews, region: String(p.region), engagementRate: p.engagementRate, avgVideoLengthSec: p.avgVideoLengthSec }); return { estimatedMonthlyPayout: r.estimatedMonthlyPayout, annualPayout: r.annualPayout, rpm: r.rpm }; },
  "time-to-value-calculator": (p) => { const r = calculateTimeToValue({ totalDaysToValue: p.totalDaysToValue, targetDays: p.targetDays, completedUsers: p.completedUsers, totalUsers: p.totalUsers }); return { averageDaysToValue: r.averageDaysToValue, onTrackPercent: r.onTrackPercent, status: r.status, daysGap: r.daysGap }; },
  "trial-to-paid-calculator": (p) => { const r = calculateTrialToPaid({ trialSignups: p.trialSignups, paidConversions: p.paidConversions }); return { conversionRate: r.conversionRate, notConverted: r.notConverted }; },
  "twitch-revenue-calculator": (p) => { const r = calculateTwitchRevenue({ avgViewers: p.avgViewers, streamHoursPerMonth: p.streamHoursPerMonth, subCount: p.subCount, subPrice: p.subPrice, adRevenuePerHour: p.adRevenuePerHour, bitsRevenuePerMonth: p.bitsRevenuePerMonth }); return { monthlySubRevenue: r.monthlySubRevenue, monthlyAdRevenue: r.monthlyAdRevenue, monthlyBitsRevenue: r.monthlyBitsRevenue, monthlyTotal: r.monthlyTotal, annualRevenue: r.annualRevenue, revenuePerStreamHour: r.revenuePerStreamHour }; },
  "unit-economics-dashboard-calculator": (p) => { const r = calculateUnitEconomicsDashboard({ cac: p.cac, ltv: p.ltv, arpu: p.arpu, grossMargin: p.grossMargin, churnRate: p.churnRate, customerCount: p.customerCount }); return { ltvCacRatio: r.ltvCacRatio, contributionMargin: r.contributionMargin, paybackPeriodMonths: r.paybackPeriodMonths, mrr: r.mrr, grossProfitPerCustomer: r.grossProfitPerCustomer }; },
  "youtube-ad-revenue-calculator": (p) => { const r = calculateYouTubeAdRevenue({ viewsPerMonth: p.viewsPerMonth, rpm: p.rpm }); return { monthlyRevenue: r.monthlyRevenue, annualRevenue: r.annualRevenue, revenuePerThousandViews: r.revenuePerThousandViews }; },
};
